name: Build and Deploy Microservices

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      # 1. Descargar código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Login DockerHub
      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Configurar Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      #################################################
      # CURSOS SERVICE
      #################################################

      # 4. Compilar cursos-service
      - name: Build cursos-service
        working-directory: ./cursos-service
        run: mvn clean package -DskipTests

      # 5. Construir imagen cursos-service
      - name: Docker build cursos-service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cursos-service:latest ./cursos-service

      # 6. Push cursos-service
      - name: Push cursos-service
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cursos-service:latest

      #################################################
      # INSCRIPCIONES SERVICE
      #################################################

      # 7. Compilar inscripciones-service
      - name: Build inscripciones-service
        working-directory: ./inscripciones-service
        run: mvn clean package -DskipTests

      # 8. Construir imagen inscripciones-service
      - name: Docker build inscripciones-service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/inscripciones-service:latest ./inscripciones-service

      # 9. Push inscripciones-service
      - name: Push inscripciones-service
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/inscripciones-service:latest

      #################################################
      # AWS
      #################################################

      # 10. Configurar AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # 11. Configurar SSH
      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      #################################################
      # DEPLOY EC2
      #################################################

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.USER_SERVER }}@${{ secrets.EC2_HOST }} << 'EOF'

            # Login DockerHub
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            # Ir carpeta proyecto
            cd ~/plataforma-educativa

            # Descargar últimas imágenes
            docker compose pull

            # Reiniciar servicios
            docker compose down
            docker compose up -d

          EOF
